- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "ignition.msgs.Clock"
  direction: IGN_TO_ROS

- ros_topic_name: "/joint_states"
  gz_topic_name: "/world/empty/model/slam_robo/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "ignition.msgs.Model"
  direction: IGN_TO_ROS

- ros_topic_name: "/tf"
  gz_topic_name: "/model/slam_robo/tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "ignition.msgs.Pose_V"
  direction: IGN_TO_ROS

- ros_topic_name: "/cmd_vel"
  gz_topic_name: "/model/slam_robo/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "ignition.msgs.Twist"
  direction: ROS_TO_IGN