<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="length" value="0.01" />
    <xacro:property name="breadth" value="0.1" />
    <xacro:property name="height" value="0.05" />

    <link name="camera">
        <visual>
            <geometry>
                <box size="${length} ${breadth} ${height}" />
            </geometry>
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <box size="${length} ${breadth} ${height}" />
            </geometry>
        </collision>
        <xacro:box_inertia m="0.1" x="${length}" y="${breadth}" z="${height}" 
                           o_xyz="0 0 0" o_rpy="0 0 0" />
    </link>

    <joint name="base_cam" type="fixed">
        <parent link="base_link" />
        <child link="camera" />
        <origin xyz="${(base_length+length)/2.0} 0 ${base_height/2.0}" rpy="0 0 0" />
    </joint>
    
    <link name="camera_link_optical" />
    <joint name="camera_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
        <parent link="camera"/>
        <child link="camera_link_optical"/>
    </joint>

    <gazebo reference="camera">
       <sensor name="camera" type="camera">
            <camera>
                <horizontal_fov>1.3962634</horizontal_fov>
                <image>
                    <width>640</width>
                    <height>480</height>
                    <format>R8G8B8</format>
                </image>
                <clip> <sensor>

        </sensor>
                    <near>0.1</near>
                    <far>15</far>
                </clip>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.007</stddev>
                </noise>
                <optical_frame_id>camera_link_optical</optical_frame_id>
                <camera_info_topic>camera/camera_info</camera_info_topic>
            </camera>
            <always_on>1</always_on>
            <update_rate>10</update_rate>
            <visualize>true</visualize>
            <topic>camera/image_raw</topic>            
        </sensor>
    </gazebo>
</robot>
