<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- LiDAR Link -->
  <xacro:property name="lidar_radius" value="0.1" />
  <xacro:property name="lidar_height" value="0.05" />

  <link name="lidar_link">
    <visual>
      <geometry>
        <cylinder radius="${lidar_radius}" length="${lidar_height}" />
      </geometry>
      <origin xyz="0.06 0 ${lidar_height/2.0}" rpy="0 0 0" />
      <material name="red" />
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${lidar_radius}" length="${lidar_height}" />
      </geometry>
      <origin xyz="0 0 ${lidar_height/2.0}" rpy="0 0 0" />
    </collision>
    <xacro:cylinder_inertia m="0.1" r="${lidar_radius}" l="${lidar_height}"
                            o_xyz="0 0 ${lidar_height/2.0}" o_rpy="0 0 0" />
  </link>

  <!-- LiDAR Joint (fixed on top of base_link) -->
  <joint name="lidar_joint" type="fixed">
    <parent link="base_link" />
    <child link="lidar_link" />
    <origin xyz="0.06 0 ${base_height}" rpy="0 0 0" />
  </joint>

</robot>
