<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- Properties -->
  <xacro:property name="base_length" value="0.6" />
  <xacro:property name="base_width" value="0.4" />
  <xacro:property name="base_height" value="0.2" />
  <xacro:property name="wheel_radius" value="0.1" />
  <xacro:property name="wheel_length" value="0.05" />

  <!-- Base -->
  <link name="base_footprint" />
  <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="5.0" x="${base_length}" y="${base_width}" z="${base_height}"
                           o_xyz="0 0 ${base_height / 2.0}" o_rpy="0 0 0" />
  </link>

  <!-- Wheel Macro -->
  <xacro:macro name="wheel_link" params="prefix">
    <link name="${prefix}_wheel">
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}" />
        </geometry>
        <origin xyz="0 0 0" rpy="${pi/2.0} 0 0" />
        <material name="black" />
      </visual>
      <collision>
            <geometry>
              <sphere radius="${wheel_radius}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
      </collision>
      <xacro:cylinder_inertia m="1.0" r="${wheel_radius}" l="${wheel_length}"
                                    o_xyz="0 0 0" o_rpy="${pi / 2.0} 0 0" />
    </link>
  </xacro:macro>

  <!-- Define all 4 wheels -->
  <xacro:wheel_link prefix="rear_right" />
  <xacro:wheel_link prefix="rear_left" />
  <xacro:wheel_link prefix="front_right" />
  <xacro:wheel_link prefix="front_left" />

  <!-- Fixed joint from base_footprint to base_link -->
  <joint name="footprint" type="fixed">
    <parent link="base_footprint" />
    <child link="base_link" />
    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0" />
  </joint>

  <!-- Wheel Joints -->
  <!-- Rear wheels -->
  <joint name="rear_right_wheel_joint" type="continuous">
    <parent link="base_link" />
    <child link="rear_right_wheel" />
    <origin xyz="${-base_length/4.0} ${-(base_width+wheel_length)/2.0} 0" rpy="0 0 0" />
    <axis xyz="0 1 0" />
  </joint>

  <joint name="rear_left_wheel_joint" type="continuous">
    <parent link="base_link" />
    <child link="rear_left_wheel" />
    <origin xyz="${-base_length/4.0} ${(base_width+wheel_length)/2.0} 0" rpy="0 0 0" />
    <axis xyz="0 1 0" />
  </joint>

  <!-- Front wheels -->
  <joint name="front_right_wheel_joint" type="continuous">
    <parent link="base_link" />
    <child link="front_right_wheel" />
    <origin xyz="${base_length/4.0} ${-(base_width+wheel_length)/2.0} 0" rpy="0 0 0" />
    <axis xyz="0 1 0" />
  </joint>

  <joint name="front_left_wheel_joint" type="continuous">
    <parent link="base_link" />
    <child link="front_left_wheel" />
    <origin xyz="${base_length/4.0} ${(base_width+wheel_length)/2.0} 0" rpy="0 0 0" />
    <axis xyz="0 1 0" />
  </joint>

</robot>